AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Flask API for TrovaPrezzi Scraper

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.8

Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: .
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Layers:
        - !Ref DependenciesLayer

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: scraper-dependencies
      Description: Dependencies for scraper function
      ContentUri: venv/
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.8
      BuildArchitecture: x86_64
      Requirements: requirements.txt
