AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Flask API for TrovaPrezzi Scraper

Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      MemorySize: 512
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: GET
    Metadata:
      BuildMethod: python3.12
      BuildProperties:
        UseContainer: false
      AWS::SAM::Cli::Artifacts:
        IgnoreFiles:
          - .gitignore
          - .git/**
          - .aws-sam/**
          - venv/**
          - __pycache__/**
      Requirements: requirements.txt

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
