AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Flask API for TrovaPrezzi Scraper

Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.8
      CodeUri: .
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: GET
